In [1]:
# Linear Regression Multiple Variables

In [2]:
# price = m1 * area + m2 * bedrooms + m3 * age + c
# price is dependent varaible
# area , bedroom , age are independent variables also know as features

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

In [10]:
df = pd.read_csv("1.csv")

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
# we will take median for row 3rd bedrooms
median_bedrooms = math.floor(df.bedrooms.median())

In [14]:
median_bedrooms

4

In [17]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [18]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
rg = linear_model.LinearRegression()

In [24]:
X = df[['area','bedrooms','age']]
Y = df.price
rg.fit(X,Y)

LinearRegression()

In [26]:
rg.coef_
# m1 , m2 , m3  are coeficients
# m1 = 112.06244194
# m2 = 23388.88007794
# m3 = -3231.71790863

array([  112.06244194, 23388.88007794, -3231.71790863])

In [28]:
rg.intercept_
# c is intercept
# c = 221323.00186540408

221323.00186540408

In [32]:
rg.predict([[3000,3,40]])
# area - 3000
# bedrooms - 3
# age - 40 years (its quite older so less price as compared to the one which exist in data frame)

array([498408.25158031])

In [33]:
# manual calculations
#  price = m1 * area + m2 * bedrooms + m3 * age + c
result = 112.06244194 * 3000 +  23388.88007794 * 3 + (-3231.71790863 * 40) + 221323.00186540408

In [34]:
result

498408.2515740241

In [35]:
rg.predict([[2500,4,5]])

array([578876.03748933])