In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math
# linear regression mostly deals for integer (numerical) data type
from word2number import w2n # for converting word to number

In [3]:
df = pd.read_csv("1_exercise.csv")

In [4]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
df.test_score = math.floor(df.test_score.median())

In [6]:
df.experience = df.experience.fillna("zero")

In [7]:
df

experience  test_score  interview_score  salary
0       zero           8                9   50000
1       zero           8                6   45000
2       five           8                7   60000
3        two           8               10   65000
4      seven           8                6   70000
5      three           8               10   62000
6        ten           8                7   72000
7     eleven           8                8   80000

In [8]:
df.experience = df.experience.apply(w2n.word_to_num)

In [11]:
df

experience  test_score  interview_score  salary
0           0           8                9   50000
1           0           8                6   45000
2           5           8                7   60000
3           2           8               10   65000
4           7           8                6   70000
5           3           8               10   62000
6          10           8                7   72000
7          11           8                8   80000

In [9]:
rg = linear_model.LinearRegression()

In [10]:
X = df[['experience','test_score','interview_score']]
Y = df.salary
rg.fit(X,Y)

LinearRegression()

In [14]:
# coefficients (m)
rg.coef_
m1 = 2704.9012934
m2 = 0 
m3 = 2307.0115725

array([2704.9012934,    0.       , 2307.0115725])

In [16]:
# intercept (c)
rg.intercept_ 
c = 31984.002722940786

In [21]:
rg.predict([[2,9,6]])

array([51235.87474472])

In [18]:
rg.predict([[12,10,10]])

array([87512.93396869])

In [20]:
result1 = 2704.9012934 * 2 + 0 * 9 + 2307.0115725 * 6 + 31984.002722940786
result1

51235.87474474079

In [22]:
result2 = 2704.9012934 * 12 + 0 * 10 + 2307.0115725 * 10 + 31984.002722940786
result2

87512.93396874079