In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [4]:
from sklearn.model_selection import  train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [16]:
# model 1 - Logisitc Regression
m1 = LogisticRegression()
m1.fit(x_train,y_train)
m1.score(x_test,y_test)

C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [17]:
# model 2 - support vector machine
m2 = SVC()
m2.fit(x_train,y_train)
m2.score(x_test,y_test)

0.9814814814814815

In [18]:
# model 3 - Random Forest Classifier
m3 = RandomForestClassifier()
m3.fit(x_train,y_train)
m3.score(x_test,y_test)

0.9703703703703703

In [20]:
from sklearn.model_selection import KFold

In [22]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
# lets use kfold for digits
def getScore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [27]:
getScore(m1,x_train,x_test,y_train,y_test) # logictic regression

C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [29]:
from sklearn.model_selection  import StratifiedKFold

In [30]:
folds = StratifiedKFold(n_splits=3)

In [35]:
scores_lg = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lg.append(getScore(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(getScore(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(getScore(RandomForestClassifier(),x_train,x_test,y_train,y_test))

C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regr

In [36]:
scores_lg

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [37]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [38]:
scores_rf

[0.9382303839732888, 0.9582637729549248, 0.9298831385642737]

In [39]:
# instead of using so much code above we can use cross validation

In [40]:
from sklearn.model_selection  import cross_val_score

In [41]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Vedant Kokane\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regr

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [42]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [43]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93611111, 0.89722222, 0.95543175, 0.96100279, 0.93871866])